INSERT INTO M1_TEMPLATE_MST
(
	TM_SEQ, CHANNEL_ID, TEMPLATE_ID
	, CHANNEL_TYPE, TEMPLATE_NAME, TEMPLATE_TITLE
	, APPROVAL_REASON, REG_USER , REG_DATE
	, APPROVAL_CODE, UPDATE_DATE, UPDATE_USER, USE_YN
)
VALUES
(
	@시퀀스, @브랜드ID, @베이스ID
	, @채널구분, @템플릿명, @템플릿제목
	, @승인결과내용, @등록자, @등록일시
	, @검수결과코드, @수정일시, @수정자, @템플릿사용여부
)


#DELIM

INSERT INTO M1_TEMPLATE_EXT_RCS
(
	TM_SEQ, TEMPLATE_ID, MESSAGEBASE_FORM_ID, AGENCY_ID
	, MESSAGEBASE_TYPE
)
VALUES
(
	@시퀀스, @베이스ID, @템플릿폼ID, @그룹ID
	, @베이스타입
)
